try to fail fast when downloading doesnt work

diff --git a/image/volume/download b/image/volume/download
--- a/image/volume/download
+++ b/image/volume/download
@@ -17,9 +17,10 @@ URL="http://ftp.musicbrainz.org/pub/musicbrainz/data/fullexport/${RELEASE_TAG}"
 wget "$URL/mbdump-cover-art-archive.tar.bz2" \
      "$URL/mbdump-derived.tar.bz2" \
      "$URL/mbdump.tar.bz2" \
-     "$URL/mbdump-cdstubs.tar.bz2" \
-    | tee /var/log/container.log
+     "$URL/mbdump-cdstubs.tar.bz2" &&
 
-# TODO: test whether the dumps have donloaded
+     echo "download success" || \
+     echo "failed to download some of the dumps!" && \
+     exit 1
 
 ls -l /dumps | tee /var/log/container.log
